# Site settings
title: Development Days
description: A blog by Huo Linhe, a bioinformatics developer, with some
  of my 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

author:
  fullname: Huo Linhe
  googleplus: https://www.google.com/+linhehuo
  github: zitsen
  twitter: zitsen
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
